# Generated by Django 4.0.2 on 2022-03-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='importaint',
            new_name='important',
        ),
    ]
